---
title: "naames2"
author: "Nicholas Baetge"
date: "3/26/2020"
output: github_document
---
# Intro

This document is primarily used to plot cast data on NAAMES 2, in support of a manuscript being prepared by James Fox. 

```{r include=FALSE}
library(tidyverse) 
library(rmarkdown)
library(knitr)
library(data.table) #these two libraries allow for data manipulation operations like join dataframes
library(zoo) #this package allows for the interpolation function
library(oce) #allows for processing and visualization of oceanographic data. Here, it is used for running integrations.
library(lattice)
library(scales)
library(gridExtra)
library(grid)
#for time
library(lubridate)
#### bar plot
library(broom)
#stat tests
library(lmtest)
library(lmodel2)
#image conversion
library(magick)
library(pdftools)
#rmarkdown tables
library(stargazer)
library(pander)
#for mapping
library(marmap)
library(ggrepel)
library(ocedata)
library(ggmap)

```


```{r include = FALSE}
custom_theme <- function() {
  theme_test(base_size = 40) %+replace%
    theme(legend.position = "top",
          legend.title = element_blank(),
          legend.spacing.x = unit(0.5,"cm"),
          legend.background = element_rect(fill = "transparent",colour = NA),
          legend.key = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA),
          plot.background = element_rect(fill = "transparent",colour = NA)) 
}

custom.colors <- c("AT39" = "#377EB8", "AT34" = "#4DAF4A", "AT38" = "#E41A1C", "AT32" = "#FF7F00", "Temperate" = "#A6CEE3", "Subpolar" = "#377EB8", "Subtropical" = "#FB9A99", "GS/Sargasso" = "#E41A1C", "Early Spring" = "#377EB8", "Late Spring" = "#4DAF4A","Early Autumn" = "#E41A1C", "Summer" = "#E41A1C", "Late Autumn" = "#FF7F00", "Gv2_2019" = "#377EB8", "WOA18_MN" = "#4DAF4A", "WOA18_AN" = "#E41A1C")

levels = c("GS/Sargasso", "Subtropical", "Temperate", "Subpolar",  "AT39-6", "AT34", "AT38", "AT32","South", "North", "Early Spring", "Late Spring","Early Autumn",  "Summer", "Late Autumn", "Gv2_2019", "WOA18_MN", "WOA18_AN","Nov", "Nov sd", "Dec", "Dec sd", "Jan", "Jan sd", "Feb", "Feb sd", "Mar", "Mar sd", "Apr", "Apr sd",  "Cruise", "ARGO")

bar.colors <- c("100 m" = "white", "CM" = "#4DAF4A",  "PAM" = "#377EB8")

```

# Import and Wrangle Data

```{r message = F}
n2_data <- read_rds("~/naames2/Input/processed_bf.2.2020.rds") %>%
  select(Cruise:Station, degree_bin, Target_Z, BactProd_C, BactAbund) %>% 
  filter(Cruise == "AT34") %>% 
  rename(bp = BactProd_C, 
         ba = BactAbund) %>% 
  mutate(degree_bin = ifelse(Station == 4, 48, degree_bin),
         bp = ifelse(bp == "NaN", NA, bp),
         ba =  ifelse(ba == "NaN", NA, ba)) %>% 
  mutate_at(vars(bp), round) %>% 
  group_by(Cruise, Station, Target_Z) 
  
bp <- n2_data %>%
  select(-ba) %>% 
  drop_na(bp) %>% 
  mutate(ave_bp =  round(mean(bp)),
         sd_bp =round(sd(bp))) %>% 
  ungroup() %>% 
  select(-bp) %>% 
  distinct()
  
ba <- n2_data %>%
  select(-bp) %>% 
  drop_na(ba) %>% 
  mutate(ave_ba =  round(mean(ba)),
         sd_ba =round(sd(ba))) %>% 
  ungroup() %>% 
  select(-ba) %>% 
  distinct()

merge <- full_join(bp, ba) %>% 
  arrange(Station, Target_Z) %>% 
  mutate(region = ifelse(degree_bin >= 50, "Subarctic", "Subtropical" ))

```

# Plot Profiles 

## Bacterial Abundance

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 12, fig.width = 20, fig.align = "center", warning = FALSE}
ba.plot <-  merge %>% 
  drop_na(ave_ba) %>% 
  filter(Target_Z <= 300) %>% 
  mutate(bin_plot = paste(degree_bin, "˚N", sep = "")) %>% 
  ggplot(aes(x = Target_Z, y = ave_ba, group = Station)) +
  geom_errorbar(aes(x = Target_Z, ymin = ave_ba - sd_ba, ymax = ave_ba + sd_ba)) +
  geom_line(size = 0.7) +
  geom_point(size = 6, shape = 21, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Bacterial Abundance, Cells L"^"-1"))), colour = "") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_colour_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  guides(colour = F, fill = F) +
  custom_theme() +
  facet_grid(region~Station+bin_plot, scales = "free") +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 90))

ba.plot
```

## Bacterial Production

```{r echo = FALSE, warning = FALSE, message = FALSE, fig.height = 12, fig.width = 20, fig.align = "center", warning = FALSE}
bp.plot <-  merge %>% 
  drop_na(ave_bp) %>% 
  filter(Target_Z <= 300) %>% 
  mutate(bin_plot = paste(degree_bin, "˚N", sep = "")) %>% 
  ggplot(aes(x = Target_Z, y = ave_bp, group = Station)) +
  geom_errorbar(aes(x = Target_Z, ymin = ave_bp - sd_bp, ymax = ave_bp + sd_bp)) +
  geom_line(size = 0.7) +
  geom_point(size = 6, shape = 21, color = "black", stroke = 1, alpha = 0.7) + 
  labs(x = expression(italic(paste("Depth, m"))), y = expression(italic(paste("Bacterial Production, nmol C L"^"-1"))), colour = "") +
  scale_x_reverse(breaks = pretty_breaks(), expand = c(0,0)) +
  coord_flip() +
  scale_y_continuous(expand = c(0,0)) +
  scale_colour_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  guides(colour = F, fill = F) +
  custom_theme() +
  facet_grid(region~Station+bin_plot, scales = "free") +
  theme(panel.spacing.x = unit(1, "cm"),
        axis.text.x = element_text(angle = 45))

bp.plot
```

```{r}
#ggsave("ba.jpg", ba.plot, device = "jpg",  width = 20, height = 12, path = "~/Desktop/") 
```

```{r}
#ggsave("bp.jpg", bp.plot, device = "jpg",  width = 20, height = 12, path = "~/Desktop/") 
```

